name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

permissions:
  contents: write  # 👈 Required for creating releases

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64,arm64]
        include:
          - goos: windows
            ext: .exe
          - goos: linux
            ext: ""
          - goos: darwin
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'

      - name: Read version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/mcui-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcui-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/mcui-${{ matrix.goos }}-${{ matrix.goarch }}*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
